### ISSUE TITLE
Need a License.

### ISSUE THREAD

**Issue by HsiangNianian** [OlivOS-Team/Extiverse#1]
Guess CC4.0?

**Comment by lunzhiPenxil** [comment]
默认为`CC-BY-SA-4.0`，但通常是作者在牌堆说明中给出的，本仓库不具有这些牌堆的著作权，所以自然不会对开源协议做任何要求

**Comment by HsiangNianian** [comment]
<details close>
<Summary>Or Unlicense?</Summary>
<pre><code>
This is free and unencumbered software released into the public domain. 
  
 Anyone is free to copy, modify, publish, use, compile, sell, or 
 distribute this software, either in source code form or as a compiled 
 binary, for any purpose, commercial or non-commercial, and by any 
 means. 
  
 In jurisdictions that recognize copyright laws, the author or authors 
 of this software dedicate any and all copyright interest in the 
 software to the public domain. We make this dedication for the benefit 
 of the public at large and to the detriment of our heirs and 
 successors. We intend this dedication to be an overt act of 
 relinquishment in perpetuity of all present and future rights to this 
 software under copyright law. 
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR 
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
 OTHER DEALINGS IN THE SOFTWARE. 
  
 For more information, please refer to <https://unlicense.org>
</code></pre>
</details>

**Comment by lunzhiPenxil** [comment]
```
First of all, this repository does not correspond to a final product software, so there is no problem with the open source agreement.
Secondly, if you think this aspect can be improved, you can submit a pull request that is bound to this issues.
Finally, most of the users here are Chinese users, so you can try to use Chinese as much as possible instead of English.
```

**Comment by HsiangNianian** [comment]
> ```
> First of all, this repository does not correspond to a final product software, so there is no problem with the open source agreement.
> Secondly, if you think this aspect can be improved, you can submit a pull request that is bound to this issues.
> Finally, most of the users here are Chinese users, so you can try to use Chinese as much as possible instead of English.
> ```

非常感谢您的提醒，我会尽可能使用中文来**回答/提出**问题。如果我发现这个库有任何可以改进的地方，我一定会提交相应的拉取请求。谢谢！

**Comment by lunzhiPenxil** [comment]
已完成
